#:kivy 2.0.0

<DeviceFrameKivy>:
    orientation: 'vertical'
    padding: '10dp'
    spacing: '5dp'
    size_hint_y: None
    height: '60dp'

    canvas.before:
        Color:
            rgba: 0.2, 0.2, 0.2, 1
        Rectangle:
            pos: self.pos
            size: self.size

    Label:
        text: root.device_name
    BoxLayout:
        size_hint_y: None
        height: '30dp'
        Label:
            text: root.device_address
        Button:
            text: '📋'
            size_hint_x: 0.2
            on_release: root.copy_to_clipboard(root.device_address)
        Button:
            text: root.rssi_bars
            size_hint_x: 0.3
            background_color: (0,0,0,0)
            on_release: root.show_rssi_popup()
