#:kivy 2.0.0

<BLEScannerScreen>:
    TabbedPanel:
        id: bottom_nav
        do_default_tab: False

        TabbedPanelItem:
            text: 'Scanner'
            ScannerScreen:
                id: scanner_screen

        TabbedPanelItem:
            id: device_screen_tab
            text: 'Device'
            DeviceScreen:
                id: device_screen

        TabbedPanelItem:
            text: 'Log'
            LogScreen:
                id: log_screen

        TabbedPanelItem:
            text: 'Wireshark'
            WiresharkScreen:
                id: wireshark_screen
