#:kivy 2.0.0

<DescriptorFrameKivy>:
    orientation: 'vertical'
    padding: '10dp'
    spacing: '5dp'
    size_hint_y: None
    height: self.minimum_height
    canvas.before:
        Color:
            rgba: app.theme.background if app else (0,0,0,1)
        Rectangle:
            pos: self.pos
            size: self.size

    Label:
        text: f"Descriptor UUID: {root.desc_uuid}"
        halign: 'left'
        text_size: self.width, None

    BoxLayout:
        size_hint_y: None
        height: '30dp'
        Label:
            text: 'Value:'
            size_hint_x: 0.2
        TextInput:
            id: value_input
            text: root.desc_value
            size_hint_x: 0.8

    BoxLayout:
        size_hint_y: None
        height: '30dp'
        spacing: '5dp'
        Button:
            id: read_button
            text: 'Read'
        Button:
            id: write_button
            text: 'Write'
