#:kivy 2.0.0

<CollapsibleFrameKivy>:
    orientation: 'vertical'
    size_hint_y: None
    height: self.minimum_height

    MDBoxLayout:
        id: header
        size_hint_y: None
        height: '48dp'

        MDRaisedButton:
            text: ('[+] ' if root.collapsed else '[-] ') + root.title
            on_release: root.toggle_collapse()

    MDBoxLayout:
        id: content
        orientation: 'vertical'
        size_hint_y: None
        height: 0 if root.collapsed else self.minimum_height
        opacity: 0 if root.collapsed else 1
        disabled: root.collapsed
        on_minimum_height: root.height = root.ids.header.height + self.height if not root.collapsed else root.ids.header.height
