#:kivy 2.0.0

<DescriptorFrameKivy>:
    orientation: 'vertical'
    padding: '10dp'
    spacing: '5dp'
    size_hint_y: None
    height: self.minimum_height
    md_bg_color: app.theme_cls.bg_light

    MDLabel:
        text: f"Descriptor UUID: {root.desc_uuid}"
        font_style: 'Body1'
        halign: 'left'
        text_size: self.width, None

    MDBoxLayout:
        size_hint_y: None
        height: '30dp'
        MDLabel:
            text: 'Value:'
            size_hint_x: 0.2
        MDTextField:
            id: value_input
            text: root.desc_value
            size_hint_x: 0.8

    MDBoxLayout:
        size_hint_y: None
        height: '30dp'
        spacing: '5dp'
        MDRaisedButton:
            id: read_button
            text: 'Read'
        MDRaisedButton:
            id: write_button
            text: 'Write'
