#:kivy 2.0.0

<DeviceFrameKivy>:
    orientation: 'vertical'
    size_hint_y: None
    size_hint_x: 1
    height: self.minimum_height

    MDCard:
        size_hint_y: None
        height: self.minimum_height
        padding: "8dp"
        on_release: app.connect_to_device(root.device)
        md_bg_color: app.theme_cls.primary_light if root.is_selected else app.theme_cls.bg_light

        MDBoxLayout:
            adaptive_height: True

            IconLeftWidget:
                icon: "bluetooth"

            MDBoxLayout:
                orientation: 'vertical'
                adaptive_height: True
                padding: "8dp"
                size_hint_x: 0.6

                MDLabel:
                    text: root.device_name
                    bold: True
                    adaptive_height: True

                MDLabel:
                    text: root.device_address
                    font_style: "Caption"
                    adaptive_height: True

                MDFlatButton:
                    text: root.service_uuids
                    font_style: "Caption"
                    adaptive_height: True
                    on_release: root.show_full_data_popup("Service UUIDs", root.full_service_uuids)
                    theme_text_color: "Primary"
                    padding: [0, 0, 0, 0]

                MDFlatButton:
                    text: root.manufacturer_data
                    font_style: "Caption"
                    adaptive_height: True
                    on_release: root.show_full_data_popup("Manufacturer Data", root.full_manufacturer_data)
                    theme_text_color: "Primary"
                    padding: [0, 0, 0, 0]

            MDBoxLayout:
                orientation: 'vertical'
                adaptive_height: True
                size_hint_x: 0.4

                MDLabel:
                    text: root.rssi_info
                    font_style: "Caption"
                    adaptive_height: True

                MDLabel:
                    text: root.period_info
                    font_style: "Caption"
                    adaptive_height: True

                MDLabel:
                    text: root.adv_flags
                    font_style: "Caption"
                    adaptive_height: True

            IconRightWidget:
                icon: "content-copy"
                on_release: root.copy_to_clipboard(root.device_address)
