#:kivy 2.0.0

<DeviceFrameKivy>:
    orientation: 'vertical'
    size_hint_y: None
    height: self.minimum_height

    MDCard:
        size_hint_y: None
        height: "108dp"
        padding: "8dp"
        on_release: app.connect_to_device(root.device)

        MDBoxLayout:
            adaptive_height: True

            IconLeftWidget:
                icon: "bluetooth"

            MDBoxLayout:
                orientation: 'vertical'
                adaptive_height: True
                padding: "8dp"

                ThreeLineAvatarIconListItem:
                    text: root.device_name
                    secondary_text: root.device_address
                    tertiary_text: root.rssi_info
                    _no_ripple_effect: True

                MDLabel:
                    text: root.period_info
                    font_style: "Caption"
                    adaptive_height: True

                MDLabel:
                    text: root.adv_flags
                    font_style: "Caption"
                    adaptive_height: True

            IconRightWidget:
                icon: "content-copy"
                on_release: root.copy_to_clipboard(root.device_address)
