#:kivy 2.0.0

<ParameterWindow>:
    title: 'Parameters'
    size_hint: 0.6, 0.4
    auto_dismiss: False

    BoxLayout:
        orientation: 'vertical'
        padding: '10dp'
        spacing: '10dp'

        TabbedPanel:
            do_default_tab: False

            TabbedPanelItem:
                text: 'Settings'

                BoxLayout:
                    orientation: 'vertical'
                    padding: '10dp'
                    spacing: '10dp'

                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: '30dp'

                        Label:
                            text: 'Bluetooth Adapter:'
                        Spinner:
                            id: adapter_spinner
                            text: 'Default'
                            values: ['Default']

                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: '30dp'

                        Label:
                            text: 'Scan Timeout:'
                        TextInput:
                            id: scan_timeout_input
                            text: '5.0'
                            multiline: False

                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: '30dp'

                        Label:
                            text: 'Theme:'
                        Spinner:
                            id: theme_spinner
                            text: 'Dark'
                            values: ['Light', 'Dark']
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: '30dp'
                        Label:
                            text: "Auto-connect to device:"
                        CheckBox:
                            id: auto_connect_checkbox
                            size_hint_x: 0.2
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: '30dp'
                        Label:
                            text: "Device name/address filter:"
                        TextInput:
                            id: auto_connect_filter_input
                            multiline: False

            TabbedPanelItem:
                text: 'Versions'

                BoxLayout:
                    orientation: 'vertical'
                    padding: '10dp'

                    Label:
                        id: versions_label
                        text: root.versions_info
                        size_hint_y: None
                        height: self.texture_size[1]


        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: '40dp'
            spacing: '10dp'

            Button:
                text: 'Restore Defaults'
                on_release: app.restore_default_parameters(root)
            Button:
                text: 'OK'
                on_release: app.update_parameters(root)
            Button:
                text: 'Cancel'
                on_release: root.dismiss()
