#:kivy 2.0.0

<WiresharkScreen>:
    orientation: 'vertical'
    padding: "5dp"

    ScrollView:
        id: wireshark_scroll_view
        bar_width: '10dp'
        scroll_type: ['bars', 'content']

        TextInput:
            id: wireshark_log_view
            text: app.wireshark_text
            readonly: True
            size_hint_y: None
            height: self.minimum_height
            background_color: app.theme.input_bg if app else (0,0,0,1)
            foreground_color: app.theme.input_fg if app else (1,1,1,1)
